# Code for 2.9(a)
Auto=read.table("Auto.data",header=T,na.strings="?")
fix(Auto)
Auto=na.omit(Auto)

# Code for 2.9(b)
attach(Auto)
range(acceleration)
range(weight)
range(displacement)
range(year)
range(mpg)
range(horsepower)

# Code for 2.9(c)
mean(mpg);sd(mpg)
mean(weight);sd(weight)
mean(acceleration);sd(acceleration)
mean(displacement);sd(displacement)
mean(year);sd(year)
mean(horsepower);sd(horsepower)


# Code for 2.9(d)
a=Auto[-c(10:85),]
mean(a$acceleration);sd(a$acceleration)
mean(a$weight);sd(a$weight)
mean(a$displacement);sd(a$displacement)
mean(a$year);sd(a$year)
mean(a$mpg);sd(a$mpg)
mean(a$horsepower);sd(a$horsepower)

# Code for 2.9(e)
par(mfrow=c(2,2))
plot(displacement,weight,main="displacement vs weight")
plot(weight,horsepower,main="weight vs horsepower")
plot(displacement,horsepower,main="displacement vs horsepower")
plot(acceleration,horsepower,main="acceleration vs horsepower")

# Code for 2.9(f)
par(mfrow=c(2,2))
plot(displacement,mpg,main="displacement vs mpg")
plot(horsepower,mpg,main="horsepower vs mpg")
plot(acceleration,mpg,main="acceleration vs mpg")
plot(weight,mpg,main="weight vs mpg")
lm.sol<-lm(mpg~weight+horsepower)
summary(lm.sol)
detach(Auto)
